# Created to destroy our infrastructure


trigger: none

pool:
  vmImage: 'windows-latest'

variables:
 rbendrg: "tf-rg-statefile"
 rbend: "jultfstorage"
 rbendcontainer: "jultfstate"
 rbendkey: "app.terraform.tfstate"

stages:     
  - stage: DeleteTheCode
    jobs:
      - job: Terraform_destroy
        steps:
          - task: TerraformInstaller@1
            displayName: Install_terraform
            inputs:
             terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: Terraform_init
            inputs:
             provider: 'azurerm'
             command: 'init'
             backendServiceArm: 'JulServicePrincipal'
             backendAzureRmResourceGroupName: '$(rbendrg)'
             backendAzureRmStorageAccountName: '$(rbend)'
             backendAzureRmContainerName: '$(rbendcontainer)'
             backendAzureRmKey: '$(rbendkey)'

          - task: TerraformTaskV4@4
            displayName: Terraform_Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'JulServicePrincipal'
              
          - task: TerraformTaskV4@4
            displayName: Terraform_destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'JulServicePrincipal'